# Generated by Django 3.2.4 on 2021-07-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('curso', models.CharField(max_length=1)),
                ('burbuja', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.CharField(max_length=200)),
                ('herramientas', models.CharField(max_length=200)),
                ('disposiivo', models.ManyToManyField(related_name='dispAlum', to='robotica.Dispositivo')),
            ],
        ),
    ]
