# Generated by Django 3.2.4 on 2021-07-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotica', '0002_auto_20210725_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='nombre',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='encuesta',
            old_name='disposiivo',
            new_name='dispositivo',
        ),
    ]
